pluginManagement {
    repositories {
        maven {
            url = uri(providers.gradleProperty('runner.repo').get())
            metadataSources { mavenPom() }
        }
    }
    plugins {
        id 'io.micronaut.runner.standalone' version providers.gradleProperty('runner.version').get()
    }
}

rootProject.name = 'published-marker-consumer'
